- name: Setup training instance
  hosts:
    - localhost
  tasks:
    - name: Update apt cache
      shell: apt-get update
    - name: Install packages
      shell: apt-get install -y unzip python3-pip htop curl git
    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
    - name: Install pipenv
      pip:
        name: pipenv
        state: latest
